name: CLA Sign Listener

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  call-central-bot:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'I have read the CLA Document and I hereby sign the CLA') }}

    uses: ./.github/workflows/cla-sign.yml

    secrets:
      CLA_BOT_TOKEN: ${{ secrets.CLA_BOT_TOKEN }}